ebikazuki/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('works.urls')),
]

#urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings_dev.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

works/urls.py
from django.urls import path
from . import views

app_name = 'works'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('genderai/',views.GenderView.as_view(), name='gender'),
    #path('genderai/func/',views.genderai, name='func'),
]

works/models.py
from django.db import models


class Sample(models.Model):
    img = models.ImageField(verbose_name='img', blank=True, null=True)

works/forms.py
from django import forms


#class ImgForm(forms.Form):
    #img = forms.ImageField(label="画像", upload_to="sample/")


from .models import Sample


class ImgForm(forms.ModelForm):
    class Meta:
        model = Sample
        fields = ('img',)

works/views.py
from django.shortcuts import render
from django.views import generic
from works.forms import ImgForm
from .models import Sample
from ebikazuki.settings import *
import shutil
import os

class IndexView(generic.TemplateView):
    template_name = "index.html"

class GenderView(generic.FormView):
    template_name = "genderai.html"
    form_class = ImgForm

    def post(self, request, *args, **kwargs):
        form = ImgForm(request.POST)

        #mediaファイルを消す
        shutil.rmtree(MEDIA_ROOT)
        os.mkdir(MEDIA_ROOT)
        sample = Sample()
        sample.img = request.FILES['img']
        sample.save()

        img = request.FILES['img']
        sample_img = sample.img
        from works.gender import gender
        man_value = gender(img)
        if man_value > 0.5 :
            result = "MAN"
        else:
            result = "WOMAN"

        return render(request, self.template_name, {
            'form': self.form_class , 'result': result ,'sample_img': sample_img
        }
                      )

works/templates/genderai.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Gender Judgement AI</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">ebikazuki.com</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">

                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead2">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Gender Judgement AI</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5"> <strong>JPEG画像をアップロードして"JUDGE"ボタンを押してください </strong></p>
                        <form method ="POST" enctype="multipart/form-data">
                          {% csrf_token %}
                          {{ form.img|add_class:'text-white btn-xl' }}
                          <button class="btn btn-primary btn-xl" type="submit">Judge</button>
                        </form>
                        <br>
                        {% if sample_img %}
                        <img src="{{ sample_img.url }}" width=35% class="image-circle"/>
                        {% else %}
                        <img width=35% class="image-circle" src="{% static 'sample/example.jpeg' %}"/>
                        {% endif %}

                        {% if result == None %}
                          <p> </p>
                        {% else %}
                          <br>
                          <p class="text-white-75 font-weight-light mb-5"> <strong> RESULT：{{result}} </strong></p>

                        {% endif %}


                    </div>
                </div>
            </div>
        </header>

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - ebikazuki.com</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

works/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>ebikazuki.com</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'css/mystyle.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">ebikazuki.com</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Works</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Contact</a></li>
                        <!--<li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>-->
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">EBIKAZUKI'S PORTFOLIO</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">はじめまして、えびかずきと申します。本業でメーカーの化工エンジニアをしながら、趣味の個人開発で人工知能技術を使ったWebアプリを制作しています。</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">About</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">About</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">近年の人工知能ブームにのって本業で機械学習をさわり始めたことをきっかけに、
                            その魅力にハマり、趣味で人工知能を使ったWebアプリの個人開発を2020年から始めました。
                            特にAI実装やAPI活用、サーバー運用などバックエンド的な処理が得意です。普段はメーカーの化工エンジニアとして、
                            データサイエンス&生産技術開発の業務をしています。</p>
                        <h4>経歴</h4>
                        <p class="text-white-50 mb-4">1989.6　愛媛県生まれ<br>
                        2012.3　広島大学 理学部卒<br>
                        2014.3　広島大学院 理学研究科修了<br>
                        2014.4〜　素材メーカー 化学工学エンジニア</p>
                        <h4>スキル</h4>
                        <p class="text-white-50 mb-4">本業での技術要素：<br>
                            Python/Tensorflow/keras/scikit-learn/Jupyter/
                            <br>統計データ分析/多変量解析/特許調査</p>
                        <p class="text-white-50 mb-4">趣味での技術要素：<br>
                            Django/Flask/Ruby on rails/node.js/PostgreSQL/<br>
                            AWS-EC2/GCP/Heroku/HTML/CSS/Git/Linux</p>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Works</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <h2 class="text-center mt-0">Works</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-brain text-primary mb-4"></i>
                            <a href="{% url 'works:gender' %}" class="h4 mb-2">Gender Judgement AI</a>
                            <br>
                            <p class="text-muted mb-0"><br>使用技術：<br>Tensorflow/keras/Django/Nginx /AWS-EC2
                                <br><br>人物画像を解析して男女を判定するAIアプリ。vgg16ディープラーニング学習済み
                                モデルに転移学習を施して製作しました。</p>
                            <a href="https://github.com/ebikazuki/portfolio-genderAI">github</a>

                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-running text-primary mb-4"></i>
                            <a href="https://runrun.ebikazuki.com" class="h4 mb-2">RUNRUN</a>
                            <br>
                            <p class="text-muted mb-0"><br>使用技術：<br>TwitterAPI/Django/PostgreSQL /Nginx/AWS-EC2
                                <br><br>日々のランニング距離をWeb上で管理するアプリです。TwitterAPIを使用して走行距離を自動で集計します。</p>
                            <a href="https://github.com/ebikazuki/runrun">github</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
                            <a href="https://positive-siritori.herokuapp.com" class="h4 mb-2">Positive Siritori</a>
                            <br>
                            <p class="text-muted mb-0"><br>使用技術：<br>GCP-NaturalLanguageAPI/Ruby on rails/PostgreSQL/Heroku
                                <br><br>ポジティブなワードのみを受理するしりとりアプリ。GCP自然言語処理APIの感情分析にて運用しています。<br>

                            </p>
                            <a href="https://github.com/ebikazuki/positive-siritori">github</a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-desktop text-primary mb-4"></i>
                            <a href="https://ebi-works.com" class="h4 mb-2">エビワークス</a>
                            <p class="text-muted mb-0">IT技術情報を発信する個人ブログです。</p>
                            <br>
                        </div>
                    </div>
                </div>
                    <div class="row justify-content-center">
                        <a class="btn btn-dark btn-xl js-scroll-trigger" href="#contact">Contact</a>
                    </div>
            </div>

        </section>

        <!-- Call to action-->
        <section class="page-section bg-dark text-white" id="contact">
            <div class="container text-center">
                <h2 class="mb-4">Contact</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-6 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fab fa-4x fa-twitter text-primary mb-4"></i>
                            <a href="https://twitter.com/razukabie" class="h4 mb-2">Twitter</a>
                            <p class="text-muted mb-0">お問い合わせはTwitterのDMでお願いします</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fab fa-4x fa-github text-primary mb-4"></i>
                            <a href="https://github.com/ebikazuki/" class="h4 mb-2">Github</a>
                            <p class="text-muted mb-0">ソースコードはこちら</p>
                        </div>
                    </div>
                </div>
                <br><br>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="#page-top">topへ戻る</a>
            </div>
        </section>
        
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - ebikazuki.com</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>